import 'dart:io';

import 'package:flutter/material.dart';

class LaunchRunbookPage extends StatefulWidget {
  const LaunchRunbookPage({super.key});

  @override
  State<LaunchRunbookPage> createState() => _LaunchRunbookPageState();
}

class _LaunchRunbookPageState extends State<LaunchRunbookPage> {
  static const String benchmarkDir = 'compression_benchmark';
  static const String evidenceDir = 'launch_evidence';

  bool _loading = true;
  String _status = 'Preparing launch runbook...';
  File? _latestCsv;
  int _csvCount = 0;

  @override
  void initState() {
    super.initState();
    _refresh();
  }

  Future<void> _refresh() async {
    setState(() {
      _loading = true;
      _status = 'Preparing launch runbook...';
    });

    try {
      final dir = Directory(benchmarkDir);
      if (!dir.existsSync()) {
        setState(() {
          _latestCsv = null;
          _csvCount = 0;
          _loading = false;
          _status = 'No benchmark directory found.';
        });
        return;
      }

      final csvFiles =
          dir
              .listSync()
              .whereType<File>()
              .where((f) => f.path.toLowerCase().endsWith('.csv'))
              .toList()
            ..sort((a, b) => b.lastModifiedSync().compareTo(a.lastModifiedSync()));

      setState(() {
        _latestCsv = csvFiles.isEmpty ? null : csvFiles.first;
        _csvCount = csvFiles.length;
        _loading = false;
        _status =
            csvFiles.isEmpty
                ? 'No CSV benchmark evidence available yet.'
                : 'Runbook ready. Latest evidence loaded.';
      });
    } catch (e) {
      setState(() {
        _loading = false;
        _status = 'Failed to prepare runbook: $e';
      });
    }
  }

  Future<void> _freezeEvidence() async {
    if (_latestCsv == null) {
      if (!mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('No CSV evidence available to freeze.')),
      );
      return;
    }

    try {
      final outputDir = Directory(evidenceDir);
      if (!outputDir.existsSync()) {
        outputDir.createSync(recursive: true);
      }

      final timestamp = DateTime.now();
      String two(int n) => n.toString().padLeft(2, '0');
      final tag =
          '${timestamp.year}${two(timestamp.month)}${two(timestamp.day)}_${two(timestamp.hour)}${two(timestamp.minute)}${two(timestamp.second)}';

      final csvCopy = File('${outputDir.path}/benchmark_evidence_$tag.csv');
      await _latestCsv!.copy(csvCopy.path);

      final runbookFile = File('${outputDir.path}/launch_runbook_$tag.md');
      final runbookText = '''# GETREADYJOB Launch Runbook Snapshot

Generated: ${timestamp.toIso8601String()}

## Evidence
- Source benchmark CSV: ${_latestCsv!.path}
- Frozen benchmark CSV: ${csvCopy.path}
- Total benchmark CSV files in workspace: $_csvCount

## Launch Checklist
- [x] Benchmark evidence snapshot frozen
- [ ] Final gate policy confirmed (portable-only / strict-only / require-both)
- [ ] Launch-day benchmark rerun completed
- [ ] Final release sign-off recorded

## Notes
This file is auto-generated by Launch Runbook page freeze action.
''';
      await runbookFile.writeAsString(runbookText);

      if (!mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text('Evidence frozen: ${runbookFile.path}'),
          backgroundColor: Colors.green,
        ),
      );

      setState(() {
        _status = 'Evidence package frozen at ${runbookFile.path}';
      });
    } catch (e) {
      if (!mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text('Freeze failed: $e'),
          backgroundColor: Colors.red,
        ),
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: const Color(0xFF1F2937),
        iconTheme: const IconThemeData(
          color: Color(0xFFFFC72C),
          size: 30,
        ),
        title: const Text(
          'Launch Runbook',
          style: TextStyle(color: Colors.white, fontWeight: FontWeight.bold),
        ),
        actions: [
          IconButton(
            icon: const Icon(Icons.refresh, color: Color(0xFFFFC72C)),
            onPressed: _loading ? null : _refresh,
          ),
        ],
      ),
      body: _loading
          ? const Center(child: CircularProgressIndicator())
          : Padding(
              padding: const EdgeInsets.all(16),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    _status,
                    style: const TextStyle(fontWeight: FontWeight.w600),
                  ),
                  const SizedBox(height: 14),
                  _infoCard(
                    'Latest Benchmark CSV',
                    _latestCsv?.path ?? 'No benchmark CSV found.',
                  ),
                  const SizedBox(height: 10),
                  _infoCard('Benchmark CSV Count', '$_csvCount files'),
                  const SizedBox(height: 16),
                  ElevatedButton.icon(
                    onPressed: _freezeEvidence,
                    icon: const Icon(Icons.lock),
                    label: const Text('Freeze Evidence Package'),
                  ),
                ],
              ),
            ),
    );
  }

  Widget _infoCard(String title, String body) {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(12),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: Colors.grey.shade300),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            title,
            style: const TextStyle(fontWeight: FontWeight.bold),
          ),
          const SizedBox(height: 4),
          SelectableText(body),
        ],
      ),
    );
  }
}
