services:
  - type: web
    name: my-pdf-compressor
    env: python
    plan: free
    rootDir: render_api
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    healthCheckPath: /healthz
    autoDeploy: true
