import 'dart:async';
import 'dart:convert';
import 'dart:typed_data';

import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:share_plus/share_plus.dart';
import 'package:universal_html/html.dart' as html;

import '../Utils/share_link_utils.dart';

class UniversalShareActions extends StatelessWidget {
  final String fileName;
  final String downloadUrl;
  final String mimeType;
  final Uint8List outputBytes;
  final String? publicHttpsUrl;

  const UniversalShareActions({
    super.key,
    required this.fileName,
    required this.downloadUrl,
    required this.mimeType,
    required this.outputBytes,
    this.publicHttpsUrl,
  });

  bool _isValidPublicHttps(String? value) {
    return ShareLinkUtils.isValidShareableUrl(value);
  }

  void _showUnsupportedShareNotice(BuildContext context) {
    ScaffoldMessenger.of(context).showSnackBar(
      const SnackBar(
        content: Text(
          'Direct file attachment is not supported in this browser. Please download the file, copy the link, or use Email / Google Drive / OneDrive.',
        ),
        backgroundColor: Colors.orange,
      ),
    );
  }

  Future<void> _shareFile(BuildContext context) async {
    try {
      final xFile = XFile.fromData(
        outputBytes,
        name: fileName,
        mimeType: mimeType,
      );

      await SharePlus.instance.share(
        ShareParams(
          files: [xFile],
          subject: 'GETREADYJOB file: $fileName',
          text: 'Generated by GETREADYJOB. Download or save this file from the browser if direct attachment is not supported.',
        ),
      );
    } catch (error) {
      if (!context.mounted) return;
      if (_isValidPublicHttps(publicHttpsUrl)) {
        html.window.open(publicHttpsUrl!, '_blank');
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text('Direct attachment failed. Opened a secure file link instead.'),
            backgroundColor: Color(0xFF1F4E79),
          ),
        );
        return;
      }

      _showUnsupportedShareNotice(context);
    }
  }

  String _googleDriveSavePageDataUri() {
    final source = downloadUrl;
    final file = fileName;
    final htmlPage = '''<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Save To Google Drive</title>
  <script src="https://apis.google.com/js/platform.js" async defer></script>
  <style>
    body { font-family: Arial, sans-serif; margin: 20px; color: #123; }
    .hint { margin-top: 12px; color: #4a5568; font-size: 13px; }
  </style>
</head>
<body>
  <h3>Save To Google Drive</h3>
  <g:savetodrive src="$source" filename="$file" sitename="GETREADYJOB"></g:savetodrive>
  <p class="hint">If the button does not appear, refresh this tab once and try again.</p>
</body>
</html>''';
    return Uri.dataFromString(
      htmlPage,
      mimeType: 'text/html',
      encoding: utf8,
    ).toString();
  }

  String _oneDriveSavePageDataUri() {
    final source = downloadUrl;
    final file = fileName;
    final htmlPage = '''<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Save To OneDrive</title>
  <script src="https://js.live.net/v7.2/OneDrive.js"></script>
  <style>
    body { font-family: Arial, sans-serif; margin: 20px; color: #123; }
    .btn {
      background: #0f62fe;
      color: white;
      border: 0;
      border-radius: 8px;
      padding: 10px 14px;
      font-weight: 700;
      cursor: pointer;
    }
    .hint { margin-top: 12px; color: #4a5568; font-size: 13px; }
  </style>
</head>
<body>
  <h3>Save To OneDrive</h3>
  <button class="btn" onclick="saveNow()">Save File</button>
  <p class="hint">Uses free OneDrive Saver SDK. If popup is blocked, allow popups and try again.</p>
  <script>
    const sourceUrl = "$source";
    const sourceFile = "$file";
    function saveNow() {
      try {
        OneDrive.save({
          sourceUri: sourceUrl,
          fileName: sourceFile,
          openInNewWindow: true,
          success: function() {
            console.log('Saved to OneDrive');
          },
          progress: function() {},
          cancel: function() {},
          error: function(e) {
            console.log('OneDrive save error', e);
          }
        });
      } catch (e) {
        alert('OneDrive SDK could not start.');
      }
    }
  </script>
</body>
</html>''';
    return Uri.dataFromString(
      htmlPage,
      mimeType: 'text/html',
      encoding: utf8,
    ).toString();
  }

  Future<void> _openGoogleDriveSaver(BuildContext context) async {
    html.window.open(_googleDriveSavePageDataUri(), '_blank');
    if (!context.mounted) return;
    ScaffoldMessenger.of(context).showSnackBar(
      const SnackBar(
        content: Text('Google Drive saver opened with current file payload.'),
        backgroundColor: Color(0xFF0F766E),
      ),
    );
  }

  Future<void> _openOneDriveSaver(BuildContext context) async {
    html.window.open(_oneDriveSavePageDataUri(), '_blank');
    if (!context.mounted) return;
    ScaffoldMessenger.of(context).showSnackBar(
      const SnackBar(
        content: Text('OneDrive saver opened with current file payload.'),
        backgroundColor: Color(0xFF1D4ED8),
      ),
    );
  }

  Future<void> _openWhatsAppShare(BuildContext context) async {
    final hasPublicUrl = _isValidPublicHttps(publicHttpsUrl);
    final message = hasPublicUrl
        ? 'File ready from GETREADYJOB%0A$fileName%0A$publicHttpsUrl'
        : 'File ready from GETREADYJOB: $fileName. Please open the app and use Download to attach this file.';

    final encoded = Uri.encodeComponent(message);
    html.window.open('https://wa.me/?text=$encoded', '_blank');

    if (!context.mounted) return;
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: Text(
          hasPublicUrl
              ? 'WhatsApp share opened with secure link.'
              : 'WhatsApp opened. For private local files, download first then attach in WhatsApp.',
        ),
        backgroundColor: const Color(0xFF128C7E),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        const Text(
          'Share / Cloud Save',
          style: TextStyle(
            fontSize: 13,
            fontWeight: FontWeight.w700,
            color: Color(0xFF334155),
          ),
        ),
        const SizedBox(height: 8),
        Wrap(
          spacing: 8,
          runSpacing: 8,
          children: [
            ElevatedButton.icon(
              onPressed: () => unawaited(_openWhatsAppShare(context)),
              icon: const Icon(Icons.chat_rounded, size: 16),
              label: const Text('WhatsApp'),
              style: ElevatedButton.styleFrom(
                backgroundColor: const Color(0xFF128C7E),
                foregroundColor: Colors.white,
                minimumSize: const Size(112, 36),
              ),
            ),
            OutlinedButton.icon(
              onPressed: () => unawaited(_openGoogleDriveSaver(context)),
              icon: const Icon(Icons.cloud_upload_rounded, size: 16),
              style: OutlinedButton.styleFrom(
                foregroundColor: const Color(0xFF0F766E),
                side: const BorderSide(color: Color(0xFF0F766E)),
                minimumSize: const Size(112, 36),
              ),
              label: const Text('Google Drive'),
            ),
            OutlinedButton.icon(
              onPressed: () => unawaited(_openOneDriveSaver(context)),
              icon: const Icon(Icons.cloud_done_rounded, size: 16),
              style: OutlinedButton.styleFrom(
                foregroundColor: const Color(0xFF1D4ED8),
                side: const BorderSide(color: Color(0xFF1D4ED8)),
                minimumSize: const Size(112, 36),
              ),
              label: const Text('OneDrive'),
            ),
            TextButton.icon(
              onPressed: () => unawaited(_shareFile(context)),
              icon: const Icon(Icons.share_rounded, size: 16),
              label: const Text('More Share'),
            ),
          ],
        ),
      ],
    );
  }
}
